# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Eilish Fox
# Description of the Site
description: Explore my designs, builds, analysis, and other work.
# URL of Image of the Site
site-image: /assets/images/DahliaBackground.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/Little%20Fox.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/DahliaBackground.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: eilishfox@proton.me
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: eilish-anne-fox
github_username:  EilishFox
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: Eilish Fox

# Name of the Author
author-name: Eilish Fox
# URL for the Image of the Author
author-image: /assets/images/Me.jpg
# 60 Words About the Author
author-about: "Hello! I live in New York. I have a BA degree in Psychology (concentrations: cognition and animal behavior). I enjoy being curious and creative. I especially like when my creativity leads to solutions for problems. I love animals, of all kinds! My work history is predominantly teaching."
author-about-short: "BA, Psychology"
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/eilishfox

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
